//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SevenWonders.WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public int Id { get; set; }
        public System.DateTime Timestamp { get; set; }
        public string Text { get; set; }
        public int ManagerId { get; set; }
        public int QuestionId { get; set; }
    
        public virtual Manager Manager { get; set; }
        public virtual Question Question { get; set; }
    }
}
