//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SevenWonders.WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reservation()
        {
            this.Tours = new HashSet<Tour>();
        }
    
        public int Id { get; set; }
        public int PersonAmount { get; set; }
        public System.DateTime LeaveDate { get; set; }
        public System.DateTime ReturnDate { get; set; }
        public int RoomId { get; set; }
        public int LeaveScheduleId { get; set; }
        public int ReturnSchedueId { get; set; }
        public bool IsDeleted { get; set; }
        public bool WithoutFood { get; set; }
    
        public virtual Room Room { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tour> Tours { get; set; }
        public virtual Schedule LeaveSchedule { get; set; }
        public virtual Schedule ReturnSchedule { get; set; }
    }
}
