//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SevenWonders.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tour
    {
        public int Id { get; set; }
        public System.DateTime CreationDate { get; set; }
        public decimal TotalPrice { get; set; }
        public bool IsDeleted { get; set; }
        public int ReservationId { get; set; }
        public int CustomerId { get; set; }
        public int TourStateId { get; set; }
        public Nullable<int> Manager_Id { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Manager Manager { get; set; }
        public virtual Reservation Reservation { get; set; }
        public virtual TourState TourState { get; set; }
    }
}
